/*
 * Created by SharpDevelop.
 * User: sergi
 * Date: 15/06/2016
 * Time: 10:30
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
namespace BW_tool
{
	partial class Entralink_DreamWorld
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.ComboBox speciesbox;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.GroupBox Move;
		private System.Windows.Forms.ComboBox movebox;
		private System.Windows.Forms.RadioButton atkC;
		private System.Windows.Forms.RadioButton atkB;
		private System.Windows.Forms.RadioButton atkA;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.RadioButton gnd_none;
		private System.Windows.Forms.RadioButton gnd_male;
		private System.Windows.Forms.RadioButton gnd_female;
		private System.Windows.Forms.Label area_label;
		private System.Windows.Forms.Button ok_but;
		private System.Windows.Forms.Button cancel_but;
		private System.Windows.Forms.Label exclusive_label;
		private System.Windows.Forms.ComboBox moveboxC;
		private System.Windows.Forms.ComboBox moveboxA;
		private System.Windows.Forms.ComboBox pgl_region_box;
		private System.Windows.Forms.Label move_lab;
		private System.Windows.Forms.Label region_lab;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.speciesbox = new System.Windows.Forms.ComboBox();
			this.label1 = new System.Windows.Forms.Label();
			this.Move = new System.Windows.Forms.GroupBox();
			this.move_lab = new System.Windows.Forms.Label();
			this.region_lab = new System.Windows.Forms.Label();
			this.pgl_region_box = new System.Windows.Forms.ComboBox();
			this.movebox = new System.Windows.Forms.ComboBox();
			this.moveboxC = new System.Windows.Forms.ComboBox();
			this.moveboxA = new System.Windows.Forms.ComboBox();
			this.atkC = new System.Windows.Forms.RadioButton();
			this.atkB = new System.Windows.Forms.RadioButton();
			this.atkA = new System.Windows.Forms.RadioButton();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.gnd_none = new System.Windows.Forms.RadioButton();
			this.gnd_male = new System.Windows.Forms.RadioButton();
			this.gnd_female = new System.Windows.Forms.RadioButton();
			this.area_label = new System.Windows.Forms.Label();
			this.ok_but = new System.Windows.Forms.Button();
			this.cancel_but = new System.Windows.Forms.Button();
			this.exclusive_label = new System.Windows.Forms.Label();
			this.Move.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.SuspendLayout();
			// 
			// speciesbox
			// 
			this.speciesbox.FormattingEnabled = true;
			this.speciesbox.Location = new System.Drawing.Point(5, 94);
			this.speciesbox.Name = "speciesbox";
			this.speciesbox.Size = new System.Drawing.Size(196, 21);
			this.speciesbox.TabIndex = 0;
			this.speciesbox.SelectedIndexChanged += new System.EventHandler(this.SpeciesboxSelectedIndexChanged);
			// 
			// label1
			// 
			this.label1.Location = new System.Drawing.Point(11, 70);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(54, 21);
			this.label1.TabIndex = 1;
			this.label1.Text = "种族";
			this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Move
			// 
			this.Move.Controls.Add(this.move_lab);
			this.Move.Controls.Add(this.region_lab);
			this.Move.Controls.Add(this.pgl_region_box);
			this.Move.Controls.Add(this.movebox);
			this.Move.Controls.Add(this.moveboxC);
			this.Move.Controls.Add(this.moveboxA);
			this.Move.Controls.Add(this.atkC);
			this.Move.Controls.Add(this.atkB);
			this.Move.Controls.Add(this.atkA);
			this.Move.Location = new System.Drawing.Point(5, 121);
			this.Move.Name = "Move";
			this.Move.Size = new System.Drawing.Size(196, 96);
			this.Move.TabIndex = 2;
			this.Move.TabStop = false;
			this.Move.Text = "招式";
			// 
			// move_lab
			// 
			this.move_lab.Location = new System.Drawing.Point(7, 45);
			this.move_lab.Name = "move_lab";
			this.move_lab.Size = new System.Drawing.Size(42, 23);
			this.move_lab.TabIndex = 8;
			this.move_lab.Text = "招式";
			// 
			// region_lab
			// 
			this.region_lab.Location = new System.Drawing.Point(7, 25);
			this.region_lab.Name = "region_lab";
			this.region_lab.Size = new System.Drawing.Size(42, 23);
			this.region_lab.TabIndex = 7;
			this.region_lab.Text = "区域";
			// 
			// pgl_region_box
			// 
			this.pgl_region_box.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.pgl_region_box.FormattingEnabled = true;
			this.pgl_region_box.Items.AddRange(new object[] {
			"全部",
			"全部",
			"全部",
			"全部",
			"全部",
			"全部",
			"全部",
			"日、韩",
			"日、韩",
			"日、韩",
			"日、韩",
			"日、韩",
			"日、韩",
			"日、韩",
			"日、美、欧",
			"日",
			"日",
			"日",
			"全部",
			"全部",
			"全部",
			"韩",
			"全部",
			"欧",
			"日",
			"日、韩",
			"全部",
			"全部",
			"日、美、欧 (用于德、意、英)",
			"韩",
			"日",
			"日",
			"日",
			"美、欧 (仅用于美)",
			"美、欧 (仅用于美)",
			"美、欧 (仅用于美)",
			"日",
			"美、欧",
			"美、欧",
			"日、韩",
			"美、欧",
			"美、欧",
			"美、欧"});
			this.pgl_region_box.Location = new System.Drawing.Point(52, 19);
			this.pgl_region_box.Name = "pgl_region_box";
			this.pgl_region_box.Size = new System.Drawing.Size(119, 21);
			this.pgl_region_box.TabIndex = 6;
			// 
			// movebox
			// 
			this.movebox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.movebox.FormattingEnabled = true;
			this.movebox.Items.AddRange(new object[] {
			"----------------------",
			"拍击",
			"空手劈",
			"连环巴掌",
			"连续拳",
			"百万吨重拳",
			"聚宝功",
			"火焰拳",
			"冰冻拳",
			"雷电拳",
			"抓",
			"夹住",
			"断头钳",
			"旋风刀",
			"剑舞",
			"居合斩",
			"起风",
			"翅膀攻击",
			"吹飞",
			"飞翔",
			"绑紧",
			"摔打",
			"藤鞭",
			"踩踏",
			"二连踢",
			"百万吨重踢",
			"飞踢",
			"回旋踢",
			"泼沙",
			"头锤",
			"角撞",
			"乱击",
			"角钻",
			"撞击",
			"泰山压顶",
			"紧束",
			"猛撞",
			"大闹一番",
			"舍身冲撞",
			"摇尾巴",
			"毒针",
			"双针",
			"飞弹针",
			"瞪眼",
			"咬住",
			"叫声",
			"吼叫",
			"唱歌",
			"超音波",
			"音爆",
			"定身法",
			"溶解液",
			"火花",
			"喷射火焰",
			"白雾",
			"水枪",
			"水炮",
			"冲浪",
			"冰冻光束",
			"暴风雪",
			"幻象光线",
			"泡沫光线",
			"极光束",
			"破坏光线",
			"啄",
			"啄钻",
			"地狱翻滚",
			"踢倒",
			"双倍奉还",
			"地球上投",
			"怪力",
			"吸取",
			"超级吸取",
			"寄生种子",
			"生长",
			"飞叶快刀",
			"日光束",
			"毒粉",
			"麻痹粉",
			"催眠粉",
			"花瓣舞",
			"吐丝",
			"龙之怒",
			"火焰旋涡",
			"电击",
			"十万伏特",
			"电磁波",
			"打雷",
			"落石",
			"地震",
			"地裂",
			"挖洞",
			"剧毒",
			"混乱",
			"超能力",
			"催眠术",
			"瑜伽姿势",
			"高速移动",
			"电光一闪",
			"愤怒",
			"瞬间移动",
			"黑夜魔影",
			"模仿",
			"刺耳声",
			"影子分身",
			"自我再生",
			"变硬",
			"变小",
			"烟幕",
			"奇异之光",
			"不参加",
			"变圆",
			"屏障",
			"光墙",
			"黑雾",
			"反射壁",
			"聚气",
			"忍耐",
			"节拍器",
			"鹦鹉学舌",
			"自爆",
			"炸蛋",
			"舌舔",
			"浊雾",
			"污泥攻击",
			"骨棒",
			"大字爆炎",
			"攀瀑",
			"贝壳夹击",
			"高速星星",
			"火箭头锤",
			"尖刺加农炮",
			"缠绕",
			"瞬间失忆",
			"折弯汤匙",
			"生蛋",
			"飞膝踢",
			"大蛇瞪眼",
			"食梦",
			"毒瓦斯",
			"投球",
			"吸血",
			"恶魔之吻",
			"神鸟猛击",
			"变身",
			"泡沫",
			"迷昏拳",
			"蘑菇孢子",
			"闪光",
			"精神波",
			"跃起",
			"溶化",
			"蟹钳锤",
			"大爆炸",
			"乱抓",
			"骨头回力镖",
			"睡觉",
			"岩崩",
			"必杀门牙",
			"棱角化",
			"纹理",
			"三重攻击",
			"愤怒门牙",
			"劈开",
			"替身",
			"挣扎",
			"写生",
			"三连踢",
			"小偷",
			"蛛网",
			"心之眼",
			"恶梦",
			"火焰轮",
			"打鼾",
			"诅咒",
			"抓狂",
			"纹理２",
			"气旋攻击",
			"棉孢子",
			"起死回生",
			"怨恨",
			"细雪",
			"守住",
			"音速拳",
			"鬼面",
			"出奇一击",
			"天使之吻",
			"腹鼓",
			"污泥炸弹",
			"掷泥",
			"章鱼桶炮",
			"撒菱",
			"电磁炮",
			"识破",
			"同命",
			"灭亡之歌",
			"冰冻之风",
			"看穿",
			"骨棒乱打",
			"锁定",
			"逆鳞",
			"沙暴",
			"终极吸取",
			"挺住",
			"撒娇",
			"滚动",
			"点到为止",
			"虚张声势",
			"喝牛奶",
			"电光",
			"连斩",
			"钢翼",
			"黑色目光",
			"迷人",
			"梦话",
			"治愈铃声",
			"返还",
			"礼物",
			"迁怒",
			"神秘守护",
			"分担痛楚",
			"神圣之火",
			"震级",
			"爆裂拳",
			"超级角击",
			"龙息",
			"接棒",
			"再来一次",
			"追打",
			"高速旋转",
			"甜甜香气",
			"铁尾",
			"金属爪",
			"借力摔",
			"晨光",
			"光合作用",
			"月光",
			"觉醒力量",
			"十字劈",
			"龙卷风",
			"求雨",
			"大晴天",
			"咬碎",
			"镜面反射",
			"自我暗示",
			"神速",
			"原始之力",
			"暗影球",
			"预知未来",
			"碎岩",
			"潮旋",
			"围攻",
			"击掌奇袭",
			"吵闹",
			"蓄力",
			"喷出",
			"吞下",
			"热风",
			"冰雹",
			"无理取闹",
			"吹捧",
			"鬼火",
			"临别礼物",
			"硬撑",
			"真气拳",
			"清醒",
			"看我嘛",
			"自然之力",
			"充电",
			"挑衅",
			"帮助",
			"戏法",
			"扮演",
			"祈愿",
			"借助",
			"扎根",
			"蛮力",
			"魔法反射",
			"回收利用",
			"报复",
			"劈瓦",
			"哈欠",
			"拍落",
			"蛮干",
			"喷火",
			"特性互换",
			"封印",
			"焕然一新",
			"怨念",
			"抢夺",
			"秘密之力",
			"潜水",
			"猛推",
			"保护色",
			"萤火",
			"洁净光芒",
			"薄雾球",
			"羽毛舞",
			"摇晃舞",
			"火焰踢",
			"玩泥巴",
			"冰球",
			"尖刺臂",
			"偷懒",
			"巨声",
			"剧毒牙",
			"撕裂爪",
			"爆炸烈焰",
			"加农水炮",
			"彗星拳",
			"惊吓",
			"气象球",
			"芳香治疗",
			"假哭",
			"空气利刃",
			"过热",
			"气味侦测",
			"岩石封锁",
			"银色旋风",
			"金属音",
			"草笛",
			"挠痒",
			"宇宙力量",
			"喷水",
			"信号光束",
			"暗影拳",
			"神通力",
			"冲天拳",
			"流沙地狱",
			"绝对零度",
			"浊流",
			"种子机关枪",
			"燕返",
			"冰锥",
			"铁壁",
			"挡路",
			"长嚎",
			"龙爪",
			"疯狂植物",
			"健美",
			"弹跳",
			"泥巴射击",
			"毒尾",
			"渴望",
			"伏特攻击",
			"魔法叶",
			"玩水",
			"冥想",
			"叶刃",
			"龙之舞",
			"岩石爆击",
			"电击波",
			"水之波动",
			"破灭之愿",
			"精神突进",
			"羽栖",
			"重力",
			"奇迹之眼",
			"唤醒巴掌",
			"臂锤",
			"陀螺球",
			"治愈之愿",
			"盐水",
			"自然之恩",
			"佯攻",
			"啄食",
			"顺风",
			"点穴",
			"金属爆炸",
			"急速折返",
			"近身战",
			"以牙还牙",
			"恶意追击",
			"查封",
			"投掷",
			"精神转移",
			"王牌",
			"回复封锁",
			"绞紧",
			"力量戏法",
			"胃液",
			"幸运咒语",
			"抢先一步",
			"仿效",
			"力量互换",
			"防守互换",
			"惩罚",
			"珍藏",
			"烦恼种子",
			"突袭",
			"毒菱",
			"心灵互换",
			"水流环",
			"电磁飘浮",
			"闪焰冲锋",
			"发劲",
			"波导弹",
			"岩石打磨",
			"毒击",
			"恶之波动",
			"暗袭要害",
			"水流尾",
			"种子炸弹",
			"空气斩",
			"十字剪",
			"虫鸣",
			"龙之波动",
			"龙之俯冲",
			"力量宝石",
			"吸取拳",
			"真空波",
			"真气弹",
			"能量球",
			"勇鸟猛攻",
			"大地之力",
			"掉包",
			"终极冲击",
			"诡计",
			"子弹拳",
			"雪崩",
			"冰砾",
			"暗影爪",
			"雷电牙",
			"冰冻牙",
			"火焰牙",
			"影子偷袭",
			"泥巴炸弹",
			"精神利刃",
			"意念头锤",
			"镜光射击",
			"加农光炮",
			"攀岩",
			"名镜",
			"戏法空间",
			"流星群",
			"放电",
			"喷烟",
			"飞叶风暴",
			"强力鞭打",
			"岩石炮",
			"十字毒刃",
			"垃圾射击",
			"铁头",
			"磁铁炸弹",
			"尖石攻击",
			"诱惑",
			"隐形岩",
			"打草结",
			"日常",
			"制裁光砾",
			"虫咬",
			"充电光束",
			"木槌",
			"水流喷射",
			"攻击指令",
			"防御指令",
			"回复指令",
			"双刃头锤",
			"二连击",
			"时光咆哮",
			"亚空裂斩",
			"新月舞",
			"捏碎",
			"熔岩风暴",
			"暗黑洞",
			"种子闪光",
			"奇异之风",
			"暗影潜袭",
			"磨爪",
			"广域防守",
			"防守平分",
			"力量平分",
			"奇妙空间",
			"精神冲击",
			"毒液冲击",
			"身体轻量化",
			"愤怒粉",
			"意念移物",
			"魔法空间",
			"击落",
			"山岚摔",
			"烈焰溅射",
			"污泥波",
			"蝶舞",
			"重磅冲撞",
			"同步干扰",
			"电球",
			"浸水",
			"蓄能焰袭",
			"盘蜷",
			"下盘踢",
			"酸液炸弹",
			"欺诈",
			"单纯光束",
			"找伙伴",
			"您先请",
			"轮唱",
			"回声",
			"逐步击破",
			"清除之烟",
			"辅助力量",
			"快速防守",
			"交换场地",
			"热水",
			"破壳",
			"治愈波动",
			"祸不单行",
			"自由落体",
			"换档",
			"巴投",
			"烧尽",
			"延后",
			"杂技",
			"镜面属性",
			"报仇",
			"搏命",
			"传递礼物",
			"炼狱",
			"水之誓约",
			"火之誓约",
			"草之誓约",
			"伏特替换",
			"虫之抵抗",
			"重踏",
			"冰息",
			"龙尾",
			"自我激励",
			"电网",
			"疯狂伏特",
			"直冲钻",
			"二连劈",
			"爱心印章",
			"木角",
			"圣剑",
			"贝壳刃",
			"高温重压",
			"青草搅拌器",
			"疯狂滚压",
			"棉花防守",
			"暗黑爆破",
			"精神击破",
			"扫尾拍打",
			"暴风",
			"爆炸头突击",
			"齿轮飞盘",
			"火焰弹",
			"高科技光炮",
			"古老之歌",
			"神秘之剑",
			"冰封世界",
			"雷击",
			"青焰",
			"火之舞",
			"冰冻伏特",
			"极寒冷焰",
			"大声咆哮",
			"冰柱坠击",
			"Ｖ热焰",
			"交错火焰",
			"交错闪电"});
			this.movebox.Location = new System.Drawing.Point(52, 42);
			this.movebox.Name = "movebox";
			this.movebox.Size = new System.Drawing.Size(119, 21);
			this.movebox.TabIndex = 3;
			// 
			// moveboxC
			// 
			this.moveboxC.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.moveboxC.FormattingEnabled = true;
			this.moveboxC.Items.AddRange(new object[] {
			"----------------------",
			"拍击",
			"空手劈",
			"连环巴掌",
			"连续拳",
			"百万吨重拳",
			"聚宝功",
			"火焰拳",
			"冰冻拳",
			"雷电拳",
			"抓",
			"夹住",
			"断头钳",
			"旋风刀",
			"剑舞",
			"居合斩",
			"起风",
			"翅膀攻击",
			"吹飞",
			"飞翔",
			"绑紧",
			"摔打",
			"藤鞭",
			"踩踏",
			"二连踢",
			"百万吨重踢",
			"飞踢",
			"回旋踢",
			"泼沙",
			"头锤",
			"角撞",
			"乱击",
			"角钻",
			"撞击",
			"泰山压顶",
			"紧束",
			"猛撞",
			"大闹一番",
			"舍身冲撞",
			"摇尾巴",
			"毒针",
			"双针",
			"飞弹针",
			"瞪眼",
			"咬住",
			"叫声",
			"吼叫",
			"唱歌",
			"超音波",
			"音爆",
			"定身法",
			"溶解液",
			"火花",
			"喷射火焰",
			"白雾",
			"水枪",
			"水炮",
			"冲浪",
			"冰冻光束",
			"暴风雪",
			"幻象光线",
			"泡沫光线",
			"极光束",
			"破坏光线",
			"啄",
			"啄钻",
			"地狱翻滚",
			"踢倒",
			"双倍奉还",
			"地球上投",
			"怪力",
			"吸取",
			"超级吸取",
			"寄生种子",
			"生长",
			"飞叶快刀",
			"日光束",
			"毒粉",
			"麻痹粉",
			"催眠粉",
			"花瓣舞",
			"吐丝",
			"龙之怒",
			"火焰旋涡",
			"电击",
			"十万伏特",
			"电磁波",
			"打雷",
			"落石",
			"地震",
			"地裂",
			"挖洞",
			"剧毒",
			"混乱",
			"超能力",
			"催眠术",
			"瑜伽姿势",
			"高速移动",
			"电光一闪",
			"愤怒",
			"瞬间移动",
			"黑夜魔影",
			"模仿",
			"刺耳声",
			"影子分身",
			"自我再生",
			"变硬",
			"变小",
			"烟幕",
			"奇异之光",
			"不参加",
			"变圆",
			"屏障",
			"光墙",
			"黑雾",
			"反射壁",
			"聚气",
			"忍耐",
			"节拍器",
			"鹦鹉学舌",
			"自爆",
			"炸蛋",
			"舌舔",
			"浊雾",
			"污泥攻击",
			"骨棒",
			"大字爆炎",
			"攀瀑",
			"贝壳夹击",
			"高速星星",
			"火箭头锤",
			"尖刺加农炮",
			"缠绕",
			"瞬间失忆",
			"折弯汤匙",
			"生蛋",
			"飞膝踢",
			"大蛇瞪眼",
			"食梦",
			"毒瓦斯",
			"投球",
			"吸血",
			"恶魔之吻",
			"神鸟猛击",
			"变身",
			"泡沫",
			"迷昏拳",
			"蘑菇孢子",
			"闪光",
			"精神波",
			"跃起",
			"溶化",
			"蟹钳锤",
			"大爆炸",
			"乱抓",
			"骨头回力镖",
			"睡觉",
			"岩崩",
			"必杀门牙",
			"棱角化",
			"纹理",
			"三重攻击",
			"愤怒门牙",
			"劈开",
			"替身",
			"挣扎",
			"写生",
			"三连踢",
			"小偷",
			"蛛网",
			"心之眼",
			"恶梦",
			"火焰轮",
			"打鼾",
			"诅咒",
			"抓狂",
			"纹理２",
			"气旋攻击",
			"棉孢子",
			"起死回生",
			"怨恨",
			"细雪",
			"守住",
			"音速拳",
			"鬼面",
			"出奇一击",
			"天使之吻",
			"腹鼓",
			"污泥炸弹",
			"掷泥",
			"章鱼桶炮",
			"撒菱",
			"电磁炮",
			"识破",
			"同命",
			"灭亡之歌",
			"冰冻之风",
			"看穿",
			"骨棒乱打",
			"锁定",
			"逆鳞",
			"沙暴",
			"终极吸取",
			"挺住",
			"撒娇",
			"滚动",
			"点到为止",
			"虚张声势",
			"喝牛奶",
			"电光",
			"连斩",
			"钢翼",
			"黑色目光",
			"迷人",
			"梦话",
			"治愈铃声",
			"返还",
			"礼物",
			"迁怒",
			"神秘守护",
			"分担痛楚",
			"神圣之火",
			"震级",
			"爆裂拳",
			"超级角击",
			"龙息",
			"接棒",
			"再来一次",
			"追打",
			"高速旋转",
			"甜甜香气",
			"铁尾",
			"金属爪",
			"借力摔",
			"晨光",
			"光合作用",
			"月光",
			"觉醒力量",
			"十字劈",
			"龙卷风",
			"求雨",
			"大晴天",
			"咬碎",
			"镜面反射",
			"自我暗示",
			"神速",
			"原始之力",
			"暗影球",
			"预知未来",
			"碎岩",
			"潮旋",
			"围攻",
			"击掌奇袭",
			"吵闹",
			"蓄力",
			"喷出",
			"吞下",
			"热风",
			"冰雹",
			"无理取闹",
			"吹捧",
			"鬼火",
			"临别礼物",
			"硬撑",
			"真气拳",
			"清醒",
			"看我嘛",
			"自然之力",
			"充电",
			"挑衅",
			"帮助",
			"戏法",
			"扮演",
			"祈愿",
			"借助",
			"扎根",
			"蛮力",
			"魔法反射",
			"回收利用",
			"报复",
			"劈瓦",
			"哈欠",
			"拍落",
			"蛮干",
			"喷火",
			"特性互换",
			"封印",
			"焕然一新",
			"怨念",
			"抢夺",
			"秘密之力",
			"潜水",
			"猛推",
			"保护色",
			"萤火",
			"洁净光芒",
			"薄雾球",
			"羽毛舞",
			"摇晃舞",
			"火焰踢",
			"玩泥巴",
			"冰球",
			"尖刺臂",
			"偷懒",
			"巨声",
			"剧毒牙",
			"撕裂爪",
			"爆炸烈焰",
			"加农水炮",
			"彗星拳",
			"惊吓",
			"气象球",
			"芳香治疗",
			"假哭",
			"空气利刃",
			"过热",
			"气味侦测",
			"岩石封锁",
			"银色旋风",
			"金属音",
			"草笛",
			"挠痒",
			"宇宙力量",
			"喷水",
			"信号光束",
			"暗影拳",
			"神通力",
			"冲天拳",
			"流沙地狱",
			"绝对零度",
			"浊流",
			"种子机关枪",
			"燕返",
			"冰锥",
			"铁壁",
			"挡路",
			"长嚎",
			"龙爪",
			"疯狂植物",
			"健美",
			"弹跳",
			"泥巴射击",
			"毒尾",
			"渴望",
			"伏特攻击",
			"魔法叶",
			"玩水",
			"冥想",
			"叶刃",
			"龙之舞",
			"岩石爆击",
			"电击波",
			"水之波动",
			"破灭之愿",
			"精神突进",
			"羽栖",
			"重力",
			"奇迹之眼",
			"唤醒巴掌",
			"臂锤",
			"陀螺球",
			"治愈之愿",
			"盐水",
			"自然之恩",
			"佯攻",
			"啄食",
			"顺风",
			"点穴",
			"金属爆炸",
			"急速折返",
			"近身战",
			"以牙还牙",
			"恶意追击",
			"查封",
			"投掷",
			"精神转移",
			"王牌",
			"回复封锁",
			"绞紧",
			"力量戏法",
			"胃液",
			"幸运咒语",
			"抢先一步",
			"仿效",
			"力量互换",
			"防守互换",
			"惩罚",
			"珍藏",
			"烦恼种子",
			"突袭",
			"毒菱",
			"心灵互换",
			"水流环",
			"电磁飘浮",
			"闪焰冲锋",
			"发劲",
			"波导弹",
			"岩石打磨",
			"毒击",
			"恶之波动",
			"暗袭要害",
			"水流尾",
			"种子炸弹",
			"空气斩",
			"十字剪",
			"虫鸣",
			"龙之波动",
			"龙之俯冲",
			"力量宝石",
			"吸取拳",
			"真空波",
			"真气弹",
			"能量球",
			"勇鸟猛攻",
			"大地之力",
			"掉包",
			"终极冲击",
			"诡计",
			"子弹拳",
			"雪崩",
			"冰砾",
			"暗影爪",
			"雷电牙",
			"冰冻牙",
			"火焰牙",
			"影子偷袭",
			"泥巴炸弹",
			"精神利刃",
			"意念头锤",
			"镜光射击",
			"加农光炮",
			"攀岩",
			"名镜",
			"戏法空间",
			"流星群",
			"放电",
			"喷烟",
			"飞叶风暴",
			"强力鞭打",
			"岩石炮",
			"十字毒刃",
			"垃圾射击",
			"铁头",
			"磁铁炸弹",
			"尖石攻击",
			"诱惑",
			"隐形岩",
			"打草结",
			"日常",
			"制裁光砾",
			"虫咬",
			"充电光束",
			"木槌",
			"水流喷射",
			"攻击指令",
			"防御指令",
			"回复指令",
			"双刃头锤",
			"二连击",
			"时光咆哮",
			"亚空裂斩",
			"新月舞",
			"捏碎",
			"熔岩风暴",
			"暗黑洞",
			"种子闪光",
			"奇异之风",
			"暗影潜袭",
			"磨爪",
			"广域防守",
			"防守平分",
			"力量平分",
			"奇妙空间",
			"精神冲击",
			"毒液冲击",
			"身体轻量化",
			"愤怒粉",
			"意念移物",
			"魔法空间",
			"击落",
			"山岚摔",
			"烈焰溅射",
			"污泥波",
			"蝶舞",
			"重磅冲撞",
			"同步干扰",
			"电球",
			"浸水",
			"蓄能焰袭",
			"盘蜷",
			"下盘踢",
			"酸液炸弹",
			"欺诈",
			"单纯光束",
			"找伙伴",
			"您先请",
			"轮唱",
			"回声",
			"逐步击破",
			"清除之烟",
			"辅助力量",
			"快速防守",
			"交换场地",
			"热水",
			"破壳",
			"治愈波动",
			"祸不单行",
			"自由落体",
			"换档",
			"巴投",
			"烧尽",
			"延后",
			"杂技",
			"镜面属性",
			"报仇",
			"搏命",
			"传递礼物",
			"炼狱",
			"水之誓约",
			"火之誓约",
			"草之誓约",
			"伏特替换",
			"虫之抵抗",
			"重踏",
			"冰息",
			"龙尾",
			"自我激励",
			"电网",
			"疯狂伏特",
			"直冲钻",
			"二连劈",
			"爱心印章",
			"木角",
			"圣剑",
			"贝壳刃",
			"高温重压",
			"青草搅拌器",
			"疯狂滚压",
			"棉花防守",
			"暗黑爆破",
			"精神击破",
			"扫尾拍打",
			"暴风",
			"爆炸头突击",
			"齿轮飞盘",
			"火焰弹",
			"高科技光炮",
			"古老之歌",
			"神秘之剑",
			"冰封世界",
			"雷击",
			"青焰",
			"火之舞",
			"冰冻伏特",
			"极寒冷焰",
			"大声咆哮",
			"冰柱坠击",
			"Ｖ热焰",
			"交错火焰",
			"交错闪电"});
			this.moveboxC.Location = new System.Drawing.Point(52, 64);
			this.moveboxC.Name = "moveboxC";
			this.moveboxC.Size = new System.Drawing.Size(119, 21);
			this.moveboxC.TabIndex = 5;
			// 
			// moveboxA
			// 
			this.moveboxA.DropDownStyle = System.Windows.Forms.ComboBoxStyle.Simple;
			this.moveboxA.FormattingEnabled = true;
			this.moveboxA.Items.AddRange(new object[] {
			"----------------------",
			"拍击",
			"空手劈",
			"连环巴掌",
			"连续拳",
			"百万吨重拳",
			"聚宝功",
			"火焰拳",
			"冰冻拳",
			"雷电拳",
			"抓",
			"夹住",
			"断头钳",
			"旋风刀",
			"剑舞",
			"居合斩",
			"起风",
			"翅膀攻击",
			"吹飞",
			"飞翔",
			"绑紧",
			"摔打",
			"藤鞭",
			"踩踏",
			"二连踢",
			"百万吨重踢",
			"飞踢",
			"回旋踢",
			"泼沙",
			"头锤",
			"角撞",
			"乱击",
			"角钻",
			"撞击",
			"泰山压顶",
			"紧束",
			"猛撞",
			"大闹一番",
			"舍身冲撞",
			"摇尾巴",
			"毒针",
			"双针",
			"飞弹针",
			"瞪眼",
			"咬住",
			"叫声",
			"吼叫",
			"唱歌",
			"超音波",
			"音爆",
			"定身法",
			"溶解液",
			"火花",
			"喷射火焰",
			"白雾",
			"水枪",
			"水炮",
			"冲浪",
			"冰冻光束",
			"暴风雪",
			"幻象光线",
			"泡沫光线",
			"极光束",
			"破坏光线",
			"啄",
			"啄钻",
			"地狱翻滚",
			"踢倒",
			"双倍奉还",
			"地球上投",
			"怪力",
			"吸取",
			"超级吸取",
			"寄生种子",
			"生长",
			"飞叶快刀",
			"日光束",
			"毒粉",
			"麻痹粉",
			"催眠粉",
			"花瓣舞",
			"吐丝",
			"龙之怒",
			"火焰旋涡",
			"电击",
			"十万伏特",
			"电磁波",
			"打雷",
			"落石",
			"地震",
			"地裂",
			"挖洞",
			"剧毒",
			"混乱",
			"超能力",
			"催眠术",
			"瑜伽姿势",
			"高速移动",
			"电光一闪",
			"愤怒",
			"瞬间移动",
			"黑夜魔影",
			"模仿",
			"刺耳声",
			"影子分身",
			"自我再生",
			"变硬",
			"变小",
			"烟幕",
			"奇异之光",
			"不参加",
			"变圆",
			"屏障",
			"光墙",
			"黑雾",
			"反射壁",
			"聚气",
			"忍耐",
			"节拍器",
			"鹦鹉学舌",
			"自爆",
			"炸蛋",
			"舌舔",
			"浊雾",
			"污泥攻击",
			"骨棒",
			"大字爆炎",
			"攀瀑",
			"贝壳夹击",
			"高速星星",
			"火箭头锤",
			"尖刺加农炮",
			"缠绕",
			"瞬间失忆",
			"折弯汤匙",
			"生蛋",
			"飞膝踢",
			"大蛇瞪眼",
			"食梦",
			"毒瓦斯",
			"投球",
			"吸血",
			"恶魔之吻",
			"神鸟猛击",
			"变身",
			"泡沫",
			"迷昏拳",
			"蘑菇孢子",
			"闪光",
			"精神波",
			"跃起",
			"溶化",
			"蟹钳锤",
			"大爆炸",
			"乱抓",
			"骨头回力镖",
			"睡觉",
			"岩崩",
			"必杀门牙",
			"棱角化",
			"纹理",
			"三重攻击",
			"愤怒门牙",
			"劈开",
			"替身",
			"挣扎",
			"写生",
			"三连踢",
			"小偷",
			"蛛网",
			"心之眼",
			"恶梦",
			"火焰轮",
			"打鼾",
			"诅咒",
			"抓狂",
			"纹理２",
			"气旋攻击",
			"棉孢子",
			"起死回生",
			"怨恨",
			"细雪",
			"守住",
			"音速拳",
			"鬼面",
			"出奇一击",
			"天使之吻",
			"腹鼓",
			"污泥炸弹",
			"掷泥",
			"章鱼桶炮",
			"撒菱",
			"电磁炮",
			"识破",
			"同命",
			"灭亡之歌",
			"冰冻之风",
			"看穿",
			"骨棒乱打",
			"锁定",
			"逆鳞",
			"沙暴",
			"终极吸取",
			"挺住",
			"撒娇",
			"滚动",
			"点到为止",
			"虚张声势",
			"喝牛奶",
			"电光",
			"连斩",
			"钢翼",
			"黑色目光",
			"迷人",
			"梦话",
			"治愈铃声",
			"返还",
			"礼物",
			"迁怒",
			"神秘守护",
			"分担痛楚",
			"神圣之火",
			"震级",
			"爆裂拳",
			"超级角击",
			"龙息",
			"接棒",
			"再来一次",
			"追打",
			"高速旋转",
			"甜甜香气",
			"铁尾",
			"金属爪",
			"借力摔",
			"晨光",
			"光合作用",
			"月光",
			"觉醒力量",
			"十字劈",
			"龙卷风",
			"求雨",
			"大晴天",
			"咬碎",
			"镜面反射",
			"自我暗示",
			"神速",
			"原始之力",
			"暗影球",
			"预知未来",
			"碎岩",
			"潮旋",
			"围攻",
			"击掌奇袭",
			"吵闹",
			"蓄力",
			"喷出",
			"吞下",
			"热风",
			"冰雹",
			"无理取闹",
			"吹捧",
			"鬼火",
			"临别礼物",
			"硬撑",
			"真气拳",
			"清醒",
			"看我嘛",
			"自然之力",
			"充电",
			"挑衅",
			"帮助",
			"戏法",
			"扮演",
			"祈愿",
			"借助",
			"扎根",
			"蛮力",
			"魔法反射",
			"回收利用",
			"报复",
			"劈瓦",
			"哈欠",
			"拍落",
			"蛮干",
			"喷火",
			"特性互换",
			"封印",
			"焕然一新",
			"怨念",
			"抢夺",
			"秘密之力",
			"潜水",
			"猛推",
			"保护色",
			"萤火",
			"洁净光芒",
			"薄雾球",
			"羽毛舞",
			"摇晃舞",
			"火焰踢",
			"玩泥巴",
			"冰球",
			"尖刺臂",
			"偷懒",
			"巨声",
			"剧毒牙",
			"撕裂爪",
			"爆炸烈焰",
			"加农水炮",
			"彗星拳",
			"惊吓",
			"气象球",
			"芳香治疗",
			"假哭",
			"空气利刃",
			"过热",
			"气味侦测",
			"岩石封锁",
			"银色旋风",
			"金属音",
			"草笛",
			"挠痒",
			"宇宙力量",
			"喷水",
			"信号光束",
			"暗影拳",
			"神通力",
			"冲天拳",
			"流沙地狱",
			"绝对零度",
			"浊流",
			"种子机关枪",
			"燕返",
			"冰锥",
			"铁壁",
			"挡路",
			"长嚎",
			"龙爪",
			"疯狂植物",
			"健美",
			"弹跳",
			"泥巴射击",
			"毒尾",
			"渴望",
			"伏特攻击",
			"魔法叶",
			"玩水",
			"冥想",
			"叶刃",
			"龙之舞",
			"岩石爆击",
			"电击波",
			"水之波动",
			"破灭之愿",
			"精神突进",
			"羽栖",
			"重力",
			"奇迹之眼",
			"唤醒巴掌",
			"臂锤",
			"陀螺球",
			"治愈之愿",
			"盐水",
			"自然之恩",
			"佯攻",
			"啄食",
			"顺风",
			"点穴",
			"金属爆炸",
			"急速折返",
			"近身战",
			"以牙还牙",
			"恶意追击",
			"查封",
			"投掷",
			"精神转移",
			"王牌",
			"回复封锁",
			"绞紧",
			"力量戏法",
			"胃液",
			"幸运咒语",
			"抢先一步",
			"仿效",
			"力量互换",
			"防守互换",
			"惩罚",
			"珍藏",
			"烦恼种子",
			"突袭",
			"毒菱",
			"心灵互换",
			"水流环",
			"电磁飘浮",
			"闪焰冲锋",
			"发劲",
			"波导弹",
			"岩石打磨",
			"毒击",
			"恶之波动",
			"暗袭要害",
			"水流尾",
			"种子炸弹",
			"空气斩",
			"十字剪",
			"虫鸣",
			"龙之波动",
			"龙之俯冲",
			"力量宝石",
			"吸取拳",
			"真空波",
			"真气弹",
			"能量球",
			"勇鸟猛攻",
			"大地之力",
			"掉包",
			"终极冲击",
			"诡计",
			"子弹拳",
			"雪崩",
			"冰砾",
			"暗影爪",
			"雷电牙",
			"冰冻牙",
			"火焰牙",
			"影子偷袭",
			"泥巴炸弹",
			"精神利刃",
			"意念头锤",
			"镜光射击",
			"加农光炮",
			"攀岩",
			"名镜",
			"戏法空间",
			"流星群",
			"放电",
			"喷烟",
			"飞叶风暴",
			"强力鞭打",
			"岩石炮",
			"十字毒刃",
			"垃圾射击",
			"铁头",
			"磁铁炸弹",
			"尖石攻击",
			"诱惑",
			"隐形岩",
			"打草结",
			"日常",
			"制裁光砾",
			"虫咬",
			"充电光束",
			"木槌",
			"水流喷射",
			"攻击指令",
			"防御指令",
			"回复指令",
			"双刃头锤",
			"二连击",
			"时光咆哮",
			"亚空裂斩",
			"新月舞",
			"捏碎",
			"熔岩风暴",
			"暗黑洞",
			"种子闪光",
			"奇异之风",
			"暗影潜袭",
			"磨爪",
			"广域防守",
			"防守平分",
			"力量平分",
			"奇妙空间",
			"精神冲击",
			"毒液冲击",
			"身体轻量化",
			"愤怒粉",
			"意念移物",
			"魔法空间",
			"击落",
			"山岚摔",
			"烈焰溅射",
			"污泥波",
			"蝶舞",
			"重磅冲撞",
			"同步干扰",
			"电球",
			"浸水",
			"蓄能焰袭",
			"盘蜷",
			"下盘踢",
			"酸液炸弹",
			"欺诈",
			"单纯光束",
			"找伙伴",
			"您先请",
			"轮唱",
			"回声",
			"逐步击破",
			"清除之烟",
			"辅助力量",
			"快速防守",
			"交换场地",
			"热水",
			"破壳",
			"治愈波动",
			"祸不单行",
			"自由落体",
			"换档",
			"巴投",
			"烧尽",
			"延后",
			"杂技",
			"镜面属性",
			"报仇",
			"搏命",
			"传递礼物",
			"炼狱",
			"水之誓约",
			"火之誓约",
			"草之誓约",
			"伏特替换",
			"虫之抵抗",
			"重踏",
			"冰息",
			"龙尾",
			"自我激励",
			"电网",
			"疯狂伏特",
			"直冲钻",
			"二连劈",
			"爱心印章",
			"木角",
			"圣剑",
			"贝壳刃",
			"高温重压",
			"青草搅拌器",
			"疯狂滚压",
			"棉花防守",
			"暗黑爆破",
			"精神击破",
			"扫尾拍打",
			"暴风",
			"爆炸头突击",
			"齿轮飞盘",
			"火焰弹",
			"高科技光炮",
			"古老之歌",
			"神秘之剑",
			"冰封世界",
			"雷击",
			"青焰",
			"火之舞",
			"冰冻伏特",
			"极寒冷焰",
			"大声咆哮",
			"冰柱坠击",
			"Ｖ热焰",
			"交错火焰",
			"交错闪电"});
			this.moveboxA.Location = new System.Drawing.Point(52, 19);
			this.moveboxA.Name = "moveboxA";
			this.moveboxA.Size = new System.Drawing.Size(119, 21);
			this.moveboxA.TabIndex = 4;
			// 
			// atkC
			// 
			this.atkC.Location = new System.Drawing.Point(6, 61);
			this.atkC.Name = "atkC";
			this.atkC.Size = new System.Drawing.Size(104, 24);
			this.atkC.TabIndex = 2;
			this.atkC.TabStop = true;
			this.atkC.Text = "C";
			this.atkC.UseVisualStyleBackColor = true;
			this.atkC.CheckedChanged += new System.EventHandler(this.AtkCCheckedChanged);
			// 
			// atkB
			// 
			this.atkB.Location = new System.Drawing.Point(6, 40);
			this.atkB.Name = "atkB";
			this.atkB.Size = new System.Drawing.Size(104, 24);
			this.atkB.TabIndex = 1;
			this.atkB.TabStop = true;
			this.atkB.Text = "B";
			this.atkB.UseVisualStyleBackColor = true;
			this.atkB.CheckedChanged += new System.EventHandler(this.AtkBCheckedChanged);
			// 
			// atkA
			// 
			this.atkA.Location = new System.Drawing.Point(6, 19);
			this.atkA.Name = "atkA";
			this.atkA.Size = new System.Drawing.Size(104, 24);
			this.atkA.TabIndex = 0;
			this.atkA.TabStop = true;
			this.atkA.Text = "A";
			this.atkA.UseVisualStyleBackColor = true;
			this.atkA.CheckedChanged += new System.EventHandler(this.AtkACheckedChanged);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.Add(this.gnd_none);
			this.groupBox1.Controls.Add(this.gnd_male);
			this.groupBox1.Controls.Add(this.gnd_female);
			this.groupBox1.Location = new System.Drawing.Point(5, 223);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(96, 94);
			this.groupBox1.TabIndex = 3;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "性别";
			// 
			// gnd_none
			// 
			this.gnd_none.Location = new System.Drawing.Point(6, 61);
			this.gnd_none.Name = "gnd_none";
			this.gnd_none.Size = new System.Drawing.Size(84, 24);
			this.gnd_none.TabIndex = 6;
			this.gnd_none.TabStop = true;
			this.gnd_none.Text = "无性别";
			this.gnd_none.UseVisualStyleBackColor = true;
			this.gnd_none.CheckedChanged += new System.EventHandler(this.Gnd_noneCheckedChanged);
			// 
			// gnd_male
			// 
			this.gnd_male.Location = new System.Drawing.Point(6, 19);
			this.gnd_male.Name = "gnd_male";
			this.gnd_male.Size = new System.Drawing.Size(72, 24);
			this.gnd_male.TabIndex = 4;
			this.gnd_male.TabStop = true;
			this.gnd_male.Text = "雄性";
			this.gnd_male.UseVisualStyleBackColor = true;
			this.gnd_male.CheckedChanged += new System.EventHandler(this.Gnd_maleCheckedChanged);
			// 
			// gnd_female
			// 
			this.gnd_female.Location = new System.Drawing.Point(6, 40);
			this.gnd_female.Name = "gnd_female";
			this.gnd_female.Size = new System.Drawing.Size(72, 24);
			this.gnd_female.TabIndex = 5;
			this.gnd_female.TabStop = true;
			this.gnd_female.Text = "雌性";
			this.gnd_female.UseVisualStyleBackColor = true;
			this.gnd_female.CheckedChanged += new System.EventHandler(this.Gnd_femaleCheckedChanged);
			// 
			// area_label
			// 
			this.area_label.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.area_label.Location = new System.Drawing.Point(5, 9);
			this.area_label.Name = "area_label";
			this.area_label.Size = new System.Drawing.Size(196, 60);
			this.area_label.TabIndex = 4;
			this.area_label.Text = "梦世界区域";
			this.area_label.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// ok_but
			// 
			this.ok_but.Location = new System.Drawing.Point(117, 255);
			this.ok_but.Name = "ok_but";
			this.ok_but.Size = new System.Drawing.Size(75, 23);
			this.ok_but.TabIndex = 5;
			this.ok_but.Text = "确认";
			this.ok_but.UseVisualStyleBackColor = true;
			this.ok_but.Click += new System.EventHandler(this.Ok_butClick);
			// 
			// cancel_but
			// 
			this.cancel_but.Location = new System.Drawing.Point(117, 284);
			this.cancel_but.Name = "cancel_but";
			this.cancel_but.Size = new System.Drawing.Size(75, 23);
			this.cancel_but.TabIndex = 6;
			this.cancel_but.Text = "取消";
			this.cancel_but.UseVisualStyleBackColor = true;
			this.cancel_but.Click += new System.EventHandler(this.Cancel_butClick);
			// 
			// exclusive_label
			// 
			this.exclusive_label.ForeColor = System.Drawing.Color.Red;
			this.exclusive_label.Location = new System.Drawing.Point(119, 69);
			this.exclusive_label.Name = "exclusive_label";
			this.exclusive_label.Size = new System.Drawing.Size(65, 23);
			this.exclusive_label.TabIndex = 7;
			this.exclusive_label.Text = "仅黑白2";
			this.exclusive_label.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// Entralink_DreamWorld
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(206, 322);
			this.Controls.Add(this.exclusive_label);
			this.Controls.Add(this.cancel_but);
			this.Controls.Add(this.ok_but);
			this.Controls.Add(this.area_label);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.Move);
			this.Controls.Add(this.label1);
			this.Controls.Add(this.speciesbox);
			this.Name = "Entralink_DreamWorld";
			this.Text = "梦世界";
			this.Move.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.ResumeLayout(false);

		}
	}
}
